-- Study Group Matcher schema. Written to run unchanged on PostgreSQL (production)
-- and on H2 in PostgreSQL mode (local development and tests).

CREATE TABLE students (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(254) NOT NULL UNIQUE,     -- stored lower-cased
    password_hash  VARCHAR(100) NOT NULL,            -- BCrypt
    display_name   VARCHAR(60)  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Real Rutgers-New Brunswick courses (seeded in V2); students choose from these.
CREATE TABLE courses (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(20)  NOT NULL UNIQUE,             -- subject:course, e.g. '198:112'
    title  VARCHAR(200) NOT NULL
);

-- Which courses each student is taking this semester.
CREATE TABLE student_courses (
    student_id  BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    course_id   BIGINT NOT NULL REFERENCES courses(id),
    PRIMARY KEY (student_id, course_id)
);
CREATE INDEX idx_student_courses_course ON student_courses (course_id);

-- Weekly recurring free time. Minutes after midnight, half-open [start, end).
-- day_of_week follows ISO-8601: 1 = Monday ... 7 = Sunday.
CREATE TABLE availability_blocks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    BIGINT   NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    day_of_week   SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    start_minute  SMALLINT NOT NULL CHECK (start_minute BETWEEN 0 AND 1439),
    end_minute    SMALLINT NOT NULL CHECK (end_minute BETWEEN 1 AND 1440),
    CHECK (start_minute < end_minute)
);
CREATE INDEX idx_availability_student ON availability_blocks (student_id);

-- A study group belongs to exactly one course.
CREATE TABLE study_groups (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id    BIGINT       NOT NULL REFERENCES courses(id),
    name         VARCHAR(80)  NOT NULL,
    description  VARCHAR(500),
    capacity     SMALLINT     NOT NULL CHECK (capacity BETWEEN 2 AND 12),
    owner_id     BIGINT       NOT NULL REFERENCES students(id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_study_groups_course ON study_groups (course_id);

CREATE TABLE group_members (
    group_id    BIGINT NOT NULL REFERENCES study_groups(id) ON DELETE CASCADE,
    student_id  BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    joined_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (group_id, student_id)
);
CREATE INDEX idx_group_members_student ON group_members (student_id);
